services:
  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT:-3000}:3000"
    volumes:
      - ./backend/api-gateway:/src
      - /src/node_modules
    environment:
      - PORT=3000
      - GENERATIONS_API_URL=${GENERATIONS_API_URL}
      - USERS_API_URL=${USERS_API_URL}
      - MONGO_EXPRESS_URL=${MONGO_EXPRESS_URL}
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - generations-api
      - users-api

  users-api:
    build:
      context: ./backend/users-api
      dockerfile: Dockerfile.dev
    container_name: users-api
    ports:
      - "${USERS_API_PORT:-5001}:5001"
    volumes:
      - ./backend/users-api:/src
      - /src/node_modules
    environment:
      - PORT=5001
    restart: unless-stopped
    networks:
      - app-network

  generations-api:
    build:
      context: ./backend/generations-api
      dockerfile: Dockerfile.dev
    container_name: generations-api
    ports:
      - "${GENERATIONS_API_PORT:-5002}:5002"
    volumes:
      - ./backend/generations-api:/src
      - /src/node_modules
    environment:
      - PORT=5002
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - mongo

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
